baseURL = "https://herolover.dev/"
languageCode = "en-us"
title = "herolover.dev"
theme = "anubis"

[author]
  name = "Anton Zhvakin"

[params]
   author = "Anton Zhvakin"
   dateFormat = "2006-01-02"
   paginationSinglePost = false
   style = "light-without-switcher"

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "contacts"
    name = "Contacts"
    url = "/contacts/"
    weight = 2

[markup.goldmark.renderer]
unsafe = true
